feat: Implement Guilds
deckerapp/decker-api pull request #9
Opened 2022-08-03 09:51 UTC by VincentRPS

closes #4, more information & implementation details on our planning board.

2022-08-04 22:17 UTC, ooliver1 requested changes

2022-08-04 22:17 UTC, ooliver1 commented on derailedapi/database.py
> +                or isinstance(v, int)
An `int` will never be `'permissions'`

2022-08-04 22:17 UTC, ooliver1 commented on derailedapi/database.py
> +                new_value = []
This is never used, right?

2022-08-04 22:17 UTC, ooliver1 commented on derailedapi/database.py
> +def objectify(data: dict[str, Any] | list[Any]) -> dict[str, Any] | list[Any]:
This should be a typevar if a passed dict returns a dict, and a passed list returns a list

2022-08-05 03:08 UTC, VincentRPS commented on derailedapi/database.py
> +                or isinstance(v, int)
the `k` isn't an int?

2022-08-05 03:09 UTC, VincentRPS commented on derailedapi/database.py
> +                new_value = []
seems like I forgot to set this value

2022-08-08 04:25 UTC, merged